### ISSUE TITLE
LiveView Native Clients: Unblock JetPack

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-native-core-jetpack#4]
Investigation the way to avoid the wrong deallocation of the native pointers.

**Comment by nelson-glauber** [comment]
We're currently investigating a way to avoid the wrong deallocation of the native pointers.

**Comment by nelson-glauber** [comment]
https://github.com/liveview-native/liveview-native-core-jetpack/pull/3

**Comment by AZholtkevych** [comment]
@nelson-glauber @Bajix guys please let me know when I can close that issue since 2 PRs still open here:
https://github.com/liveview-native/liveview-native-core-jetpack/pull/3
https://github.com/liveview-native/liveview-client-jetpack/pull/61

FYI @adam-phillips

**Comment by Bajix** [comment]
We can probably close now just because Jetpack is unblocked already, or we can wait for https://github.com/liveview-native/liveview-client-jetpack/pull/61On Aug 25, 2023, at 7:07 AM, AZholtkevych ***@***.***> wrote:﻿
@nelson-glauber @Bajix guys please let me know when I can close that issue since 2 PRs still open here:
#3
liveview-native/liveview-client-jetpack#61
FYI @adam-phillips

**Comment by AZholtkevych** [comment]
Let's wait till those merged please @Bajix FYI @nelson-glauber @adam-phillips
